import Navbar from "@/Components/Shared/Navbar";
import Footer from "@/Components/Shared/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
        <Navbar />
        <div className="h-screen">{children}</div>
        <Footer />
  </div>
  );
}
