import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>HEADER SECTION</h1>
        </header>
        {children}
        <footer>
          <h1>FOOTER SECTION</h1>
        </footer>
      </body>
    </html>
  )
}
