import SideBarDrawer from "@/Components/Shared/SideBar";

export const metadata = {
    title: "dashboard Page",
    description: "Generated by create next app",
  };

const DashboardLayout = ({children}) => {
    return (
        <div className="flex">
            <SideBarDrawer/>
            <div className="">
                {children}
            </div>
        </div>
    );
};

export default DashboardLayout;